### ISSUE TITLE
Create a Class Diagram

### ISSUE THREAD

**Issue by fireurza** [fireurza/Robbie_Robot_Shop#2]

**Comment by KF5CVK** [comment]
[RRS Class Diagram.pdf](https://github.com/fireurza/Robbie_Robot_Shop/files/191113/RRS.Class.Diagram.pdf)

[RRS Class Diagram(3).zip](https://github.com/fireurza/Robbie_Robot_Shop/files/191115/RRS.Class.Diagram.3.zip)
The zip file contains a XML document for use in draw.io online creation tool for flowcharts and stuff.  If anyone is good at these I could use some help with proper layout or suggestions for classes needed and methods within the class.  I will continue to edit with what Aaron has posted so far and update when that is complete.

**Comment by KF5CVK** [comment]
Updated...  I knwo it is wrong and I am researching but any help/suggestions will be very helpful!
[RRS Class Diagram 20160328.pdf](https://github.com/fireurza/Robbie_Robot_Shop/files/192682/RRS.Class.Diagram.20160328.pdf)
[RRS Class Diagram 20160328.zip](https://github.com/fireurza/Robbie_Robot_Shop/files/192686/RRS.Class.Diagram.20160328.zip)

**Comment by KF5CVK** [comment]
Another Update, closer to his example but still incomplete
[RRS Class Diagram 20160328 (2).zip](https://github.com/fireurza/Robbie_Robot_Shop/files/192768/RRS.Class.Diagram.20160328.2.zip)

[RRS Class Diagram 20160328 (2).pdf](https://github.com/fireurza/Robbie_Robot_Shop/files/192765/RRS.Class.Diagram.20160328.2.pdf)

**Comment by fireurza** [comment]
I don't know how to edit it but TheBoss should access sale's associate (for employee sales), robotmodel (for cost and price to generate profit), and maybe order (for number of each robot model sold.

**Comment by KF5CVK** [comment]
Final Version with Boss, BC, and SA accessing through the Shop
[RRS Class Diagram 20160330.zip](https://github.com/fireurza/Robbie_Robot_Shop/files/196007/RRS.Class.Diagram.20160330.zip)

**Comment by KF5CVK** [comment]
LOL...   I don't even have the product manager on here to create and edit parts!!

**Comment by KF5CVK** [comment]
Better...
[RRS Class Diagram 20160330(1).zip](https://github.com/fireurza/Robbie_Robot_Shop/files/196222/RRS.Class.Diagram.20160330.1.zip)
