### ISSUE TITLE
Create a Sprint Backlog

### ISSUE THREAD

**Issue by fireurza** [fireurza/Robbie_Robot_Shop#4]
This backlog is for our reference.

**Comment by fireurza** [comment]
This is on going. We need to get together in chat or in person and discuss sprint 2 soon.

**Comment by KF5CVK** [comment]
Does this sound like a good plan??  Does it cover everything??
Sprint 1 Goals - Create Parts, Create Models from parts, Basic CLI 
Sprint 2 Goals - Create/Save/Edit Orders and Customer/Employee Information
Sprint 3 Goals - Generate Reports, Basic GUI
Sprint 4 Goals - Finalize GUI and other unknown features

**Comment by KF5CVK** [comment]
Better...
[RRS Class Diagram 20160330(1).zip](https://github.com/fireurza/Robbie_Robot_Shop/files/196217/RRS.Class.Diagram.20160330.1.zip)

**Comment by KF5CVK** [comment]
If I was in in the right issue

**Comment by GasserMontaser** [comment]
Yes, great plan.
